##############################################################################
# Instruqt Github Actions Workflow
#
# This workflow file and its actions will run a validate/push/test cycle on
# one or more Instruqt tracks directories in your repo. Each job targets a
# separate directory of tracks. All the tracks in each directory must belong
# to the same organization.
#
##############################################################################
name: Production Track Test
env:
  # Set these values to match your environment. Your token should be 
  # stored as a Github secret in your tracks repo. Also make sure you 
  # have a track-slugs.yml file in your tracks directory.
  ORGANIZATION_SLUG: examples
  TRACK_DIR: instruqt-tracks
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  push:
    branches:
    # Your branch might be called main. Make sure it matches your main branch!
      - master
jobs:
  Get-Track-Slugs:
  # Fetches track slugs and ids from the track-slugs.yml file
    runs-on: ubuntu-latest
    steps:
    - run: echo "ðŸ“ Production validate/push/test job was triggered by a ${{ github.event_name }} event."
    - name: Check out repository code
      uses: actions/checkout@v2
    - id: install-yq
      run: wget https://github.com/mikefarah/yq/releases/download/v4.21.1/yq_linux_amd64 && sudo mv yq_linux_amd64 /usr/bin/yq && chmod +x /usr/bin/yq
    - id: create-matrix-data
      run: echo "TRACKS=$(yq -o j $TRACK_DIR/track-slugs.yml | jq tostring | sed -e 's/^"//' -e 's/"$//')" >> $GITHUB_ENV
    - id: set-matrix
      run: echo "::set-output name=matrix::${{ env.TRACKS }}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  Test-Prod-Tracks:
    runs-on: ubuntu-latest
    needs: Get-Track-Slugs
    strategy:
      matrix: ${{ fromJson(needs.Get-Track-Slugs.outputs.matrix) }}
    steps:
      - run: echo "ðŸ§ª Running validate/push/test cycle on prod tracks."
      - name: Check out repository code
        uses: actions/checkout@v2
      - id: install-yq
        run: wget https://github.com/mikefarah/yq/releases/download/v4.21.1/yq_linux_amd64 && sudo mv yq_linux_amd64 /usr/bin/yq && chmod +x /usr/bin/yq
      - name: Promote dev tracks to production
        uses: ./.github/actions/instruqt-track-promote
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks.slug }}
          id: ${{ matrix.tracks.id }}
      - name: Track Validate
        uses: ./.github/actions/instruqt-track-validate
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks.slug }}
      - name: Track Push
        uses: ./.github/actions/instruqt-track-push
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks.slug }}
      - name: Instruqt Track Test
        uses: ./.github/actions/instruqt-track-test
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks.slug }}
      - run: echo "ðŸ¤– This job's status is ${{ job.status }}."
